######################
## PYTHON CONTAINER ##
######################
python:
    restart: always
    build: .
    expose:
        - "8000"
    links:
        - postgres:postgres
    volumes:
        - /usr/src/app
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

#####################
## NGINX CONTAINER ##
#####################
nginx:
    restart: always
    build: ./nginx/
    ports:
        - "80:80"
    volumes:
        - static/:/www/static
    links:
        - python:python

####################
## POSTGRES CONTAINER ##
####################
postgres:
    restart: always
    image: postgres
    expose:
        - "5432"
