######################
## PYTHON CONTAINER ##
######################
python:
    restart: always
    build: .
    expose:
        - "8080"
    links:
        - postgres:postgres
    working_dir: /app
    command: /usr/local/bin/gunicorn -w 2 app:app


#####################
## NGINX CONTAINER ##
#####################
nginx:
    restart: always
    build: ./nginx/
    ports:
        - "80:80"
    links:
        - python:python

####################
## POSTGRES CONTAINER ##
####################
postgres:
    restart: always
    image: postgres
    expose:
        - "5432
